version: '3'
services:
  app:
    container_name: publisher_express
    restart: always
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: publisher_mongo
    image: mvertes/alpine-mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
